# получение объявлений
GET http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

###

POST http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token d1bb6c9f3599973bc9df794028a8a9613f7dddd3


###

GET http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b


###
POST http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

{
  "state": "closed"
}

###
GET http://127.0.0.1:8000/api/v1/partner/orders
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

###
GET http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

###
POST http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

###
POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

{
  "first_name": "S",
  "last_name": "RonSSaldo",
  "email": "123322@gmail.com",
  "password": "123@gmail.com",
  "company": "SDADD",
  "position": "DDD",
  "type": "SHOP"
}

###
POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json
#Authorization: Token 272ef3d0bcbda8b8a5f1ce2cb1bfcf983ae4071e

{
  "email": "cr7@gmail.com",
  "password": "cr7@gmail.com"
}

###
POST http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token 272ef3d0bcbda8b8a5f1ce2cb1bfcf983ae4071e

{
  "type": "SHOP"
}

###
GET http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token 272ef3d0bcbda8b8a5f1ce2cb1bfcf983ae4071e

###
POST http://127.0.0.1:8000/api/v1/user/register/confirm
Content-Type: application/json
#Authorization: Token 272ef3d0bcbda8b8a5f1ce2cb1bfcf983ae4071e

{
  "email": "gosha.jerry@gmail.com",
  "token": "272ef3d0bcbda8b8a5f1ce2cb1bfcf983ae4071e"
}
