### Registration
POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "Foo",
  "last_name": "Bar",
  "email": "email",
  "password": "ValidPassword",
  "company": "MU",
  "position": "Fw",
  "type": "CLIENT"
}

### Confrim Registration
POST http://127.0.0.1:8000/api/v1/user/register/confirm
Content-Type: application/json

{
  "email": "email",
  "token": "TokenFromMail"
}

### Login to account
POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "email",
  "password": "test1test"
}

### Get info about account
GET http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Change user info
POST http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "first_name": "Gosha",
  "last_name": "Barinov"
}

### Change user password
POST http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "password": "test1test"
}

### Get my contacts
GET http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Add my contacts
POST http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "city": "123",
  "phone": "123"
}

### Edit my contact
PUT http://127.0.0.1:8000/api/v1/user/contact/10/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "city": "456",
  "house": "2",
  "building": "3",
  "phone": "asd007"
}

### Delete my contact
DELETE http://127.0.0.1:8000/api/v1/user/contact/11/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Reset password (get a rest-token)
POST http://127.0.0.1:8000/api/v1/user/password_reset
Content-Type: application/json

{
  "email": "email"
}

### Confirm new password
POST http://127.0.0.1:8000/api/v1/user/password_reset/confirm
Content-Type: application/json

{
  "password": "test2test",
  "token": "TokenFromMail"
}









### Get all categories
GET http://127.0.0.1:8000/api/v2/category
Content-Type: application/json

### New category
POST http://127.0.0.1:8000/api/v2/category/
Content-Type: application/json

{
  "name": "s"
}

### Delete category
DELETE http://127.0.0.1:8000/api/v2/category/5/
Content-Type: application/json
