### Registration
POST http://127.0.0.1:8000/api/v1/user/registration/
Content-Type: application/json

{
  "first_name": "Foo",
  "last_name": "Bar",
  "email": "email@email.com",
  "password": "Valid1Password",
  "company": "MU",
  "position": "Fw",
  "type": "CLIENT"
}

### Confrim Registration
POST http://127.0.0.1:8000/api/v1/user/register/confirm_registration
Content-Type: application/json

{
  "email": "email",
  "token": "TokenFromMail"
}

### Login to account
POST http://127.0.0.1:8000/api/v1/user/login_account
Content-Type: application/json

{
  "email": "email",
  "password": "test1test"
}

### Get info about account
GET http://127.0.0.1:8000/api/v1/user/user_info
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Change user info
POST http://127.0.0.1:8000/api/v1/user/change_user_info/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "email": "gosha.jerry"
}

### Change user password
POST http://127.0.0.1:8000/api/v1/user/change_user_info/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "password": "test1test"
}

### Get my contacts
GET http://127.0.0.1:8000/api/v1/user/user_contacts/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Add my contacts
POST http://127.0.0.1:8000/api/v1/user/add_user_contact
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "city": "123",
  "phone": "123"
}

### Edit my contact
PATCH http://127.0.0.1:8000/api/v1/user/10/change_user_contact/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "city": "456",
  "house": "2",
  "building": "3",
  "phone": "asd007"
}

### Delete my contact
DELETE http://127.0.0.1:8000/api/v1/user/100/delete_user_contact/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Reset password (get a rest-token)
POST http://127.0.0.1:8000/api/v1/user/password_reset
Content-Type: application/json

{
  "email": "email"
}

### Confirm new password
POST http://127.0.0.1:8000/api/v1/user/password_reset/confirm
Content-Type: application/json

{
  "password": "test2test",
  "token": "TokenFromMail"
}

### Partner get state
GET http://127.0.0.1:8000/api/v1/partner/shop_info
Content-Type: application/json
Authorization: Token d023365cf17ea08e79f16428f4ee1177e739b0f1

### Partner change state
PATCH http://127.0.0.1:8000/api/v1/partner/change_shop_status/
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

{
  "state": "False"
}

### POST method for upload .yaml-file need to use by the Postman with "Body"-"form-data"
POST http://127.0.0.1:8000/api/v1/partner/add_price/
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

### Get list of orders from shop
GET http://127.0.0.1:8000/api/v1/partner/users_orders/
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

### Get list of categories
GET http://127.0.0.1:8000/api/v1/categories
Content-Type: application/json

### Get list of shop's
GET http://127.0.0.1:8000/api/v1/shops
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

### Find a product by name or category
GET http://127.0.0.1:8000/api/v1/products
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5


### Get your shopping cart
GET http://127.0.0.1:8000/api/v1/shopping_cart/basket
Content-Type: application/json
Authorization: Token d1bb6c9f3599973bc9df794028a8a9613f7dddd3

### Add product to your shopping cart
POST http://127.0.0.1:8000/api/v1/shopping_cart/add_position
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "product_info_id": 37,
  "quantity": 10
}

### Get info about item in shopping cart
GET http://127.0.0.1:8000/api/v1/shopping_cart/1/product_info/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

### Change quantity of item
PATCH http://127.0.0.1:8000/api/v1/shopping_cart/51/change_quantity/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "quantity": "True"
}

### Delete item for shopping cart
DELETE http://127.0.0.1:8000/api/v1/shopping_cart/61/delete_position/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de

### Get list of user orders
GET http://127.0.0.1:8000/api/v1/order/get_orders
Content-Type: application/json
Authorization: Token f762137d3ee85ceb7470bcb1ad53648331c9453b

### Change status of order from BASKET to NEW
POST http://127.0.0.1:8000/api/v1/order/new_order/
Content-Type: application/json
Authorization: Token 127442b31c0023df3875960e889dcc36b6de99e5

{
  "order_id": "8",
  "contact_id": "10"
}

